name: Java CI with Gradle

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  release:
    types: [created]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew downloadPalm2BetaSDK build
      - name: Build release artifacts with Gradle
        if: github.event_name == 'release'
        run: ./gradlew zipArtifacts
      - name: Stop gradle daemon
        run: ./gradlew --stop
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: build/release/*
